# Generated by Django 5.1.2 on 2024-11-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
